import React, {useEffect, useState} from 'react';
import {Button, TextField} from "@mui/material";
import './Main.css'
import Good from "../Good/Good";

const Main:React.FC = ()=> {
    const [isAuthorized, setIsAuthorized] = useState(false)
    const [inputValue, setInputValue]=useState('')
    const [res, setRes] = useState({status: false, userName: 'Позивний',  code: '', lastReport: '0'})

    const storageVal = localStorage.getItem('res')
    const parsedStorageVal = storageVal !== null ? JSON.parse(storageVal) : null

    const onSubmit = ()=>{
        if(!inputValue){
            alert('Будь ласка, введіть пароль!')
        }else {
            //make post and if 200 isAuthorized = true
            //save received autogenerated code to local storage
            //send it with each post request
            const res = {status: true, userName: 'Stealth', code: 'atrerae4a4s5r', lastReport: '1676137805431'}
            if(res.status){
                localStorage.setItem('res', JSON.stringify(res))
                setRes(res)
                setIsAuthorized(true)
                setInputValue('')
            }else{
                setInputValue('')
                alert('Ви ввели не вірний пароль. Будь ласка, повторіть спробу або зверніться до адміністратора.')
            }
        }
    }

    useEffect(()=>{
        if(parsedStorageVal !== null && parsedStorageVal.status){
            setRes(parsedStorageVal)
            setIsAuthorized(parsedStorageVal.status)
        }
    }, [])
  return (
    <div>
        {isAuthorized ? <div className={'main-page'}><Good userName={res.userName} lastReport={res.lastReport} setIsAuthorized={setIsAuthorized}/></div> :
        <div className={'login-page'}>
         <TextField type='password' label="Пароль" autoComplete="off" variant="outlined" size='small' onChange={(e)=> {setInputValue(e.target.value)}} value={inputValue}/>
         <span style={{marginLeft: '10px', lineHeight: '35px'}} >
             <Button variant="contained" onClick={onSubmit}>Увійти</Button>
         </span>
        </div>
        }
    </div>
  );
}

export default Main;
